parameters:
  name: 'check'

jobs:
- job: ${{ parameters.name }}
  displayName: check
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - template: install.yaml
    - script: cargo fetch
      displayName: cargo fetch
    - script: cargo check
      displayName: cargo check
