parameters:
  name: 'clippy'

jobs:
- job: ${{ parameters.name }}
  displayName: clippy
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - template: install.yaml
    - script: cargo fetch
      displayName: Fetch
    - script: cargo clippy -- -D warnings
      displayName: Clippy check
