parameters:
  name: 'rustfmt'

jobs:
- job: ${{ parameters.name }}
  displayName: rustfmt
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: install.yaml
    - script: rustup component add rustfmt
      displayName: Install rustfmt
    - script: cargo fmt --all -- --check
      displayName: Check formatting