parameters:
  name: 'test'

jobs:
- job: ${{ parameters.name }}
  displayName: test
  steps:
    - template: install.yaml
    - script: cargo fetch
      displayName: Fetch
    - script: cargo test --no-run
      displayName: Check test (no run)
    - script: cargo test --no-fail-fast
      displayName: Run tests