jobs:
- job: ${{ parameters.name }}
  displayName: cargo fmt
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: install.yaml
    - bash: |
        rustup component add rustfmt
      displayName: Install rustfmt
    - bash: |
        cargo fmt --all -- --check
      displayName: Check formatting